package life.majiang.community.model;

public class Nav {
    private Integer id;
    private String title;
    private String url;
    private Integer priority;
    private Long gmtCreate;
    private Long gmtModified;
    private Integer status;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NAV.TITLE
     *
     * @param title the value for NAV.TITLE
     *
     * @mbg.generated Sun Jan 10 02:53:25 CST 2021
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NAV.URL
     *
     * @return the value of NAV.URL
     *
     * @mbg.generated Sun Jan 10 02:53:25 CST 2021
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NAV.URL
     *
     * @param url the value for NAV.URL
     *
     * @mbg.generated Sun Jan 10 02:53:25 CST 2021
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NAV.PRIORITY
     *
     * @return the value of NAV.PRIORITY
     *
     * @mbg.generated Sun Jan 10 02:53:25 CST 2021
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NAV.PRIORITY
     *
     * @param priority the value for NAV.PRIORITY
     *
     * @mbg.generated Sun Jan 10 02:53:25 CST 2021
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NAV.GMT_CREATE
     *
     * @return the value of NAV.GMT_CREATE
     *
     * @mbg.generated Sun Jan 10 02:53:25 CST 2021
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NAV.GMT_CREATE
     *
     * @param gmtCreate the value for NAV.GMT_CREATE
     *
     * @mbg.generated Sun Jan 10 02:53:25 CST 2021
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NAV.GMT_MODIFIED
     *
     * @return the value of NAV.GMT_MODIFIED
     *
     * @mbg.generated Sun Jan 10 02:53:25 CST 2021
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NAV.GMT_MODIFIED
     *
     * @param gmtModified the value for NAV.GMT_MODIFIED
     *
     * @mbg.generated Sun Jan 10 02:53:25 CST 2021
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NAV.STATUS
     *
     * @return the value of NAV.STATUS
     *
     * @mbg.generated Sun Jan 10 02:53:25 CST 2021
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NAV.STATUS
     *
     * @param status the value for NAV.STATUS
     *
     * @mbg.generated Sun Jan 10 02:53:25 CST 2021
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}